name: schedule_event
on:  
  schedule:
      - cron '*/6 * * * *' #every two minutes
jobs:
  show_info:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "This is a push event on all the branches"
